In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#Get dimention
b.ndim

2

In [12]:
#Get Shape
b.shape

(2, 3)

In [15]:
#Get type
a.dtype

dtype('int32')

In [16]:
#Get size
a.itemsize

4

In [19]:
#Get total size
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [22]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [26]:
#Get a specific element [r,c]
b[1,5]

13

In [30]:
#Get a specific row
b[: ,2]

array([ 3, 10])

In [32]:
#Get a little more fancy [startindex:endindex:stepsize]
b[0, 1:6:2]

array([2, 4, 6])

In [33]:
b[1,5] = 20

In [34]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [35]:
#3d example
c = np.array([[[1,2],[2,3]]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Initializing different types of arrays

In [41]:
#All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [42]:
#All 1s matrix
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [45]:
#All any number matrix
np.full((2,2),55)

array([[55, 55],
       [55, 55]])

In [49]:
# Any other number (full_like)
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full_like(a, 4)

array([4, 4, 4])

In [55]:
#Random decimal number
np.random.rand(4,2)

array([[0.80696488, 0.24599831],
       [0.22396189, 0.41113981],
       [0.07255896, 0.30948183],
       [0.01552756, 0.16569764]])

In [70]:
#Random integer number
np.random.randint(4,7, size=(3,3))

array([[5, 4, 6],
       [5, 5, 6],
       [4, 4, 5]])

In [71]:
#The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,  3, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])